# Generated by Django 2.2 on 2021-07-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payback',
            name='date_of_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
    ]
